version: 2.1

orbs:
  architect: giantswarm/architect@5.12.1

workflows:
  test-and-push:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main
                - master
          registries-data: |-
            public gsoci.azurecr.io ACR_GSOCI_USERNAME ACR_GSOCI_PASSWORD true
            public quay.io QUAY_USERNAME QUAY_PASSWORD true
